import os
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import dh
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.backends import default_backend
import base64
import json

# Generate DH parameters (in practice, these would be pre-shared or generated by a trusted authority)
# For simplicity, we generate them once and store in a file. In a real app, they might be hard-coded or distributed securely.
PARAMETERS_FILE = "dh_parameters.pem"

def generate_dh_parameters():
    """Generate Diffie-Hellman parameters and save to file."""
    parameters = dh.generate_parameters(generator=2, key_size=2048, backend=default_backend())
    with open(PARAMETERS_FILE, "wb") as f:
        f.write(parameters.parameter_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.ParameterFormat.PKCS3
        ))
    return parameters

def load_dh_parameters():
    """Load DH parameters from file, generate if not exists."""
    if not os.path.exists(PARAMETERS_FILE):
        return generate_dh_parameters()
    with open(PARAMETERS_FILE, "rb") as f:
        return serialization.load_pem_parameters(f.read(), backend=default_backend())

def generate_dh_keypair(parameters):
    """Generate a DH private/public key pair."""
    private_key = parameters.generate_private_key()
    public_key = private_key.public_key()
    return private_key, public_key

def serialize_public_key(public_key):
    """Serialize public key to PEM format string."""
    return public_key.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo
    ).decode('utf-8')

def deserialize_public_key(public_key_pem):
    """Deserialize public key from PEM format string."""
    return serialization.load_pem_public_key(
        public_key_pem.encode('utf-8'),
        backend=default_backend()
    )

def derive_shared_key(private_key, peer_public_key):
    """Derive a shared secret using DH and then use HKDF to create an AES key."""
    shared_secret = private_key.exchange(peer_public_key)
    # Use HKDF to derive a key from the shared secret
    hkdf = HKDF(
        algorithm=hashes.SHA256(),
        length=32,  # AES-256 key
        salt=None,
        info=b'handshake data',
        backend=default_backend()
    )
    return hkdf.derive(shared_secret)

def encrypt_message(key, plaintext):
    """Encrypt plaintext using AES-GCM."""
    iv = os.urandom(12)  # GCM recommended IV length
    cipher = Cipher(algorithms.AES(key), modes.GCM(iv), backend=default_backend())
    encryptor = cipher.encryptor()
    ciphertext = encryptor.update(plaintext.encode('utf-8')) + encryptor.finalize()
    return {
        'iv': base64.b64encode(iv).decode('utf-8'),
        'ciphertext': base64.b64encode(ciphertext).decode('utf-8'),
        'tag': base64.b64encode(encryptor.tag).decode('utf-8')
    }

def decrypt_message(key, encrypted_data):
    """Decrypt ciphertext using AES-GCM."""
    iv = base64.b64decode(encrypted_data['iv'])
    ciphertext = base64.b64decode(encrypted_data['ciphertext'])
    tag = base64.b64decode(encrypted_data['tag'])
    cipher = Cipher(algorithms.AES(key), modes.GCM(iv, tag), backend=default_backend())
    decryptor = cipher.decryptor()
    plaintext = decryptor.update(ciphertext) + decryptor.finalize()
    return plaintext.decode('utf-8')